services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ../train:/datasets/train:ro
      - ../test_done:/datasets/test:ro
    networks:
      - med-net
    environment:
      APP_ROLE: api
      API_URL: http://api:8000
      TRAIN_DATA_DIR: /datasets/train
      TEST_DATA_DIR: /datasets/test
      PYTHONUNBUFFERED: "1"

  frontend:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./data:/app/data
      - ../train:/datasets/train:ro
      - ../test_done:/datasets/test:ro
    environment:
      APP_ROLE: frontend
      API_URL: http://api:8000
      TRAIN_DATA_DIR: /datasets/train
      TEST_DATA_DIR: /datasets/test
      PYTHONUNBUFFERED: "1"
    networks:
      - med-net

networks:
  med-net:
    driver: bridge
