"""Runtime helpers for loading and executing Phase 3 classifier ensembles."""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import cv2
import numpy as np
import torch

from core.preprocessor import get_preprocessor
from models.classifier import load_classifier_from_checkpoint

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MODEL_MANIFEST = REPO_ROOT / "models" / "checkpoints" / "resnet50_cv_v1" / "model_manifest.json"
IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)
WINDOWS_ABSOLUTE_PATH = re.compile(r"^[A-Za-z]:[\\/]")


@dataclass(slots=True)
class EnsemblePrediction:
    """A runtime prediction generated by the fold ensemble."""

    probability: float
    threshold: float
    disease_detected: bool
    fold_probabilities: list[float]


def resolve_model_manifest_path(explicit_path: str | Path | None = None) -> Path | None:
    """Resolve the model manifest path from argument, env var, or default path."""
    candidate = explicit_path or os.getenv("HIP_DYSPLASIA_MODEL_MANIFEST") or DEFAULT_MODEL_MANIFEST
    path = Path(candidate)
    if not path.is_absolute():
        path = (REPO_ROOT / path).resolve()
    return path if path.exists() else None


def resolve_checkpoint_path(checkpoint_value: str | Path, *, manifest_path: Path) -> Path:
    """Resolve checkpoint paths from local, relative or Windows-authored manifests."""
    raw_value = str(checkpoint_value)
    raw_path = Path(raw_value)

    if raw_path.is_absolute():
        return raw_path

    if WINDOWS_ABSOLUTE_PATH.match(raw_value):
        windows_parts = raw_value.replace("\\", "/").split("/")
        if "models" in windows_parts:
            start_index = windows_parts.index("models")
            candidate = REPO_ROOT.joinpath(*windows_parts[start_index:])
            if candidate.exists():
                return candidate.resolve()

    return (manifest_path.parent / raw_value).resolve()


def resolve_inference_device(device_name: str | None = None) -> torch.device:
    """Resolve the requested inference device safely."""
    resolved_name = device_name or os.getenv("HIP_DYSPLASIA_DEVICE") or "auto"
    if resolved_name != "auto":
        if resolved_name.startswith("cuda") and not torch.cuda.is_available():
            return torch.device("cpu")
        return torch.device(resolved_name)
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def prepare_image_tensor(image: np.ndarray, *, input_size: int) -> torch.Tensor:
    """Convert a normalized grayscale image into a normalized model tensor."""
    if image.ndim == 3 and image.shape[-1] == 1:
        image = image[..., 0]
    if image.ndim != 2:
        raise ValueError(f"Expected a 2D image for inference, got shape {list(image.shape)}")

    image = image.astype(np.float32, copy=False)
    if image.shape != (input_size, input_size):
        image = cv2.resize(image, (input_size, input_size), interpolation=cv2.INTER_AREA)

    rgb_image = np.repeat(image[..., None], 3, axis=2)
    normalized = (rgb_image - IMAGENET_MEAN) / IMAGENET_STD
    tensor = torch.from_numpy(np.transpose(normalized, (2, 0, 1))).to(dtype=torch.float32)
    return tensor.unsqueeze(0)


class HipDysplasiaEnsemble:
    """Load fold checkpoints and run ensemble inference."""

    def __init__(self, manifest_path: str | Path, *, device: str | torch.device | None = None) -> None:
        self.manifest_path = Path(manifest_path).resolve()
        self.device = resolve_inference_device(str(device) if device is not None else None)
        self.manifest = json.loads(self.manifest_path.read_text(encoding="utf-8"))
        self.input_size = int(self.manifest.get("input_size", 384))
        self.preprocessing_profile = str(self.manifest.get("preprocessing_profile", "default"))
        self.threshold = float(self.manifest.get("ensemble_threshold", 0.5))
        self.models = []

        for fold_entry in self.manifest.get("folds", []):
            checkpoint_path = resolve_checkpoint_path(
                fold_entry["checkpoint"],
                manifest_path=self.manifest_path,
            )
            model, _ = load_classifier_from_checkpoint(checkpoint_path, device=self.device)
            self.models.append(model)

        if not self.models:
            raise ValueError(f"Model manifest '{self.manifest_path}' does not contain any folds.")

    def build_preprocessor(self):
        """Construct the deterministic preprocessing pipeline expected by this ensemble."""
        return get_preprocessor(
            profile=self.preprocessing_profile,
            target_size=(self.input_size, self.input_size),
        )

    @property
    def fold_count(self) -> int:
        return len(self.models)

    @torch.no_grad()
    def predict(self, image: np.ndarray) -> EnsemblePrediction:
        tensor = prepare_image_tensor(image, input_size=self.input_size).to(self.device)
        fold_probabilities = [
            float(torch.sigmoid(model(tensor)).detach().cpu().item()) for model in self.models
        ]
        probability = float(np.mean(fold_probabilities))
        threshold = float(np.clip(self.threshold, 0.05, 0.95))
        return EnsemblePrediction(
            probability=probability,
            threshold=threshold,
            disease_detected=probability >= threshold,
            fold_probabilities=fold_probabilities,
        )
